# Generated by Django 4.2.2 on 2023-07-17 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_issue_returned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.request'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='returned_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
