# Generated by Django 4.2.2 on 2023-09-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_book_isbn_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth (YYYY-MM-DD)'),
        ),
    ]
